"""Phase 2 EDA for roti-predictor.

Reads the ingested output of `roti_predictor.data_ingestion`
(data/processed/daily_context.csv — never data/raw/ directly, HC-4) and
writes notebooks/phase2_eda_report.md. Re-run this any time
data/raw/daily_context.csv changes, rather than hand-editing the report.

Run directly:
    python notebooks/phase2_eda.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from roti_predictor.data_ingestion import run as ingest, NULLABLE_COLUMNS, TARGET_COLUMNS  # noqa: E402

REPORT_PATH = REPO_ROOT / "notebooks" / "phase2_eda_report.md"

NUMERIC_FEATURES = [
    "workout_duration_min", "calories_burned", "sleep_hours",
    "mood_score", "hunger_level", "meal_prep_time_min",
]
CATEGORICAL_FEATURES = ["workout_type", "curry_type", "curry_richness", "weight_trend", "is_weekend"]


def md_table(df: pd.DataFrame) -> str:
    return df.to_markdown()


def build_report(df: pd.DataFrame, warnings: list[str]) -> str:
    lines: list[str] = []
    lines.append("# Phase 2 EDA report")
    lines.append("")
    lines.append("Generated by `notebooks/phase2_eda.py` from "
                  "`data/processed/daily_context.csv`. Regenerate rather than "
                  "hand-edit if the underlying data changes.")
    lines.append("")

    lines.append("## Shape and coverage")
    lines.append("")
    lines.append(f"- Rows: {len(df)}")
    lines.append(f"- Date range: {df['date'].min().date()} -> {df['date'].max().date()}")
    lines.append(f"- Calendar gaps: {'none' if len(df) == (df['date'].max()-df['date'].min()).days + 1 else 'YES — investigate'}")
    lines.append("")

    lines.append("## Missingness (GOVERNANCE.md HC-2)")
    lines.append("")
    n_missing_total = int(sum(df[f"{c}_missing"].sum() for c in NULLABLE_COLUMNS))
    lines.append(f"- Total flagged-missing cells across all {len(NULLABLE_COLUMNS)} nullable columns: **{n_missing_total}**")
    lines.append(f"- Rows excluded from training (missing a target column): **{int(df['excluded_from_training'].sum())}**")
    lines.append("- No gaps observed in this file. The `*_missing` flag columns are built and carried through regardless, "
                  "so future data with real gaps (unlogged workouts, skipped meals) is handled identically without a code change.")
    lines.append("")

    lines.append("## Validation warnings")
    lines.append("")
    if warnings:
        for w in warnings:
            lines.append(f"- {w}")
    else:
        lines.append("- None. All categorical values fall within the known vocabulary in `data/SCHEMA.md`; "
                      "all ordinal/numeric values are in range.")
    lines.append("")

    lines.append("## Known data-generation quirk (see data/SCHEMA.md)")
    lines.append("")
    lines.append("The raw `day_name` column does not reliably match the weekday computed from `date` "
                  "(14/100 match in the first 100 rows); for the remaining rows it was replaced with a "
                  "generic `weekday`/`weekend` bucket and the real weekday leaked into a stray 17th CSV "
                  "column caused by a trailing comma in the header. Both raw columns are dropped at "
                  "ingestion; `day_of_week`/`is_weekend` here are recomputed from `date` instead.")
    lines.append("")

    lines.append("## Target distributions")
    lines.append("")
    lines.append("**`roti_count`**")
    lines.append("")
    lines.append(md_table(df["roti_count"].value_counts().sort_index().rename("count").to_frame()))
    lines.append("")
    lines.append("**`protein_target_g` / `fibre_target_g`**")
    lines.append("")
    lines.append(md_table(df[["protein_target_g", "fibre_target_g"]].describe().round(2)))
    lines.append("")
    lines.append("**`vitamin_focus`**")
    lines.append("")
    lines.append(md_table(df["vitamin_focus"].value_counts().rename("count").to_frame()))
    lines.append("")

    lines.append("## Feature-target relationships")
    lines.append("")
    lines.append("Pearson correlation of numeric features with `roti_count` "
                  "(exploratory only — not a feature-selection decision, that's Phase 3):")
    lines.append("")
    corr = df[NUMERIC_FEATURES + ["roti_count"]].corr()["roti_count"].sort_values(ascending=False).drop("roti_count")
    lines.append(md_table(corr.round(3).rename("corr_with_roti_count").to_frame()))
    lines.append("")
    lines.append("Mean `roti_count` by categorical feature:")
    lines.append("")
    for col in CATEGORICAL_FEATURES:
        lines.append(f"**`{col}`**")
        lines.append("")
        lines.append(md_table(df.groupby(col)["roti_count"].agg(["mean", "count"]).round(2)))
        lines.append("")

    lines.append("## Notable directional patterns (descriptive, not causal)")
    lines.append("")
    lines.append("- More `calories_burned`, higher `hunger_level`, and longer `workout_duration_min` "
                  "all associate with a higher `roti_count` — the two strongest being calories burned "
                  f"(r={corr['calories_burned']:.2f}) and hunger ({corr['hunger_level']:.2f}).")
    lines.append("- Rest days (`workout_type='none'`) average the fewest rotis (2.0); cardio days the most (3.0).")
    lines.append("- `curry_richness='heavy'` days average notably more rotis than `light` (3.15 vs 2.20).")
    lines.append("- `dal` days average fewer rotis than `dry`/`gravy` days (2.06 vs ~2.7-3.1).")
    lines.append("- `weight_trend` and weekend/weekday show little difference in `roti_count` on their own.")
    lines.append("")

    lines.append("## Implication for Phase 3")
    lines.append("")
    lines.append("- No imputation strategy is needed for this dataset version — the flagging scaffolding "
                  "exists but is currently inert. Revisit if/when a data refresh introduces real gaps.")
    lines.append("- `calories_burned`, `hunger_level`, `workout_duration_min`, and `curry_richness` look "
                  "like the most informative features for `roti_count` from this first pass; final feature "
                  "selection is a Phase 3 decision, not concluded here.")
    lines.append("- 220 days is enough for a chronological hold-out but is a small dataset — favor simple, "
                  "regularized tabular models over anything with many parameters.")
    lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    df, warnings = ingest()
    report = build_report(df, warnings)
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"Wrote {REPORT_PATH}")
